name: Automation

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  labeling:
    name: Label merge conflicts
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v2.1.0
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
